# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: whereru2_development
  pool: 5
  username: root
  password:

development_alter:
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  database: something
  username: something
  password: something
  host: cits2232.csse.uwa.edu.au


