#!/usr/bin/env bash

bootstrap_app() {

  # Bootstraps the rails process
  frozen_gems="./vendor/rubygems"

  [[ "$1" = 'install' ]] && rm -rf "$gem_directory_path"

  mkdir -p "$gem_directory_path/bin"
  
  export PATH="$gem_directory_path/bin:$PATH"
  export GEM_HOME="$gem_directory_path"
  export GEM_PATH="$gem_directory_path"
  export BUNDLE_PATH="$GEM_HOME"

  if [[ "$1" = "install" ]]; then
    echo "Installing Bundler and gems..."
    gem install bundler --no-ri --no-rdoc
    $gem_directory_path/bin/bundle install --disable-shared-gems "$GEM_HOME"
  elif [[ -n "$1" ]]; then
    echo "Running program: $@"
    name="$1"; shift
    $gem_directory_path/bin/bundle exec "$name" "$@"
  fi

}

echo "$0" | grep -q "sh" || bootstrap_app $@
